const express = require('express');
const archiver = require('archiver');
const Website = require('../models/Website');
const { auth } = require('../middleware/auth');

const router = express.Router();

const generateHtml = (website) => {
  const components = website.components || [];
  const bodyHtml = components
    .sort((a, b) => a.order - b.order)
    .map(c => {
      const comp = c.componentId;
      if (!comp) return '';
      return comp.htmlTemplate || `<section class="component-${comp.type}"><h2>${comp.name}</h2></section>`;
    })
    .join('\n');

  const css = components
    .map(c => c.componentId?.cssTemplate || '')
    .filter(Boolean)
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${website.name}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', sans-serif; }
    ${css}
  </style>
</head>
<body>
  ${bodyHtml}
</body>
</html>`;
};

router.get('/:websiteId/zip', auth, async (req, res) => {
  try {
    const website = await Website.findById(req.params.websiteId).populate('components.componentId');
    if (!website) return res.status(404).json({ message: 'Website not found' });

    const html = generateHtml(website);
    const readme = `# ${website.name}\n\nGenerated by WEPZO Platform\nModule: ${website.moduleType}\n\nDeploy this folder to any web server.\n`;

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${website.name.replace(/\s+/g, '-')}.zip"`);

    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.pipe(res);
    archive.append(html, { name: 'index.html' });
    archive.append(readme, { name: 'README.md' });
    archive.append('/* Component styles */', { name: 'styles/main.css' });
    await archive.finalize();

    website.zipExported = true;
    website.zipExportedAt = new Date();
    await website.save();
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

module.exports = router;
