import { useEffect, useMemo, useState } from 'react'
import { Globe2, Save } from 'lucide-react'
import api from '../../api/axios'

const defaultContent = {
  brand:{name:'',logo:'',primaryColor:'#ff4b12'},header:{enabled:true,homeLabel:'Home',loginLabel:'Login',getStartedLabel:'Get Started',getStartedHref:'#/register',languageLabel:'EN',links:[]},
  hero:{enabled:false,eyebrow:'',title:'',highlight:'',description:'',primaryLabel:'',primaryHref:'#/register',secondaryLabel:'',secondaryHref:'#features',demoLabel:'',demoHref:'#contact',image:'',benefits:[],reassurance:[],preview:{}},
  features:{enabled:false,eyebrow:'',title:'',description:'',items:[]},
  services:{enabled:false,items:[],trustLabel:'',readyTitle:'',readyDescription:'',readyButton:'',readyHref:'#pricing'},
  process:{enabled:false,title:'',steps:[],videoTitle:'',videoDescription:'',videoLabel:'',videoHref:'#contact',videoImage:''},
  pricing:{enabled:false,eyebrow:'',title:'',description:'',footnote:'',monthlyLabel:'Monthly',yearlyLabel:'Yearly',monthUnit:'month',yearUnit:'year',savingsLabel:'',popularLabel:'',chooseLabel:'Choose',manageLabel:'Manage plan',plans:[]},
  testimonials:{enabled:false,eyebrow:'',title:'',items:[]},faq:{enabled:false,eyebrow:'',title:'',items:[]},
  about:{enabled:false,eyebrow:'',title:'',description:'',button:'',href:'#services',stats:[]},
  contact:{enabled:false,eyebrow:'',title:'',description:'',email:'',submitLabel:'',nameLabel:'',namePlaceholder:'',emailLabel:'',emailPlaceholder:'',messageLabel:'',messagePlaceholder:'',successMessage:''},
  finalCta:{enabled:false,eyebrow:'',title:'',description:'',button:'',href:'#/register'},
  trusted:{enabled:false,title:'',brands:[]},promotions:{enabled:false,eyebrow:'',title:'',couponLabel:'',copyLabel:'',defaultButton:''},footer:{enabled:false,tagline:'',contactLabel:''},
}

function merge(defaults,value){if(Array.isArray(defaults))return Array.isArray(value)?value:defaults;if(!defaults||typeof defaults!=='object')return value===undefined?defaults:value;return Object.fromEntries(Object.entries(defaults).map(([key,child])=>[key,merge(child,value?.[key])]))}
const getPath=(object,path)=>path.split('.').reduce((value,key)=>value?.[key],object)
function setPath(object,path,value){const keys=path.split('.');const result=JSON.parse(JSON.stringify(object));let cursor=result;keys.slice(0,-1).forEach(key=>{cursor[key]=cursor[key]||{};cursor=cursor[key]});cursor[keys.at(-1)]=value;return result}

const groups=[
  {title:'Brand and navigation',fields:[['header.enabled','Show website header','checkbox'],['brand.name','Website name'],['brand.logo','Logo image URL'],['brand.primaryColor','Primary color (hex)','color'],['header.homeLabel','Home link text'],['header.loginLabel','Login button text'],['header.getStartedLabel','Get started button text'],['header.getStartedHref','Get started link'],['header.languageLabel','Language label'],['header.links','Navigation links','json']]},
  {title:'Homepage hero',fields:[['hero.enabled','Show hero section','checkbox'],['hero.eyebrow','Small label'],['hero.title','Headline'],['hero.highlight','Headline highlight'],['hero.description','Description','textarea'],['hero.image','Hero image URL (optional)','url'],['hero.primaryLabel','Primary button'],['hero.primaryHref','Primary button link'],['hero.secondaryLabel','Secondary button'],['hero.secondaryHref','Secondary button link'],['hero.demoLabel','Demo link text'],['hero.demoHref','Demo link target'],['hero.benefits','Benefit icons and labels','json'],['hero.reassurance','Trust notes','json'],['hero.preview','Dashboard preview content','json']]},
  {title:'Features',fields:[['features.enabled','Show features section','checkbox'],['features.eyebrow','Small label'],['features.title','Heading'],['features.description','Description','textarea'],['features.items','Feature cards','json']]},
  {title:'Services',fields:[['services.enabled','Show services section','checkbox'],['services.items','Service cards','json'],['services.trustLabel','Trust label'],['services.readyTitle','Callout heading'],['services.readyDescription','Callout description','textarea'],['services.readyButton','Callout button'],['services.readyHref','Callout button link']]},
  {title:'How it works',fields:[['process.enabled','Show how it works section','checkbox'],['process.title','Section heading'],['process.steps','Steps','json'],['process.videoTitle','Video heading (use {businessName} for site name)'],['process.videoDescription','Video description','textarea'],['process.videoLabel','Video button'],['process.videoHref','Video link'],['process.videoImage','Video image URL','url']]},
  {title:'Pricing',fields:[['pricing.enabled','Show pricing section','checkbox'],['pricing.eyebrow','Small label'],['pricing.title','Heading'],['pricing.description','Description','textarea'],['pricing.monthlyLabel','Monthly toggle'],['pricing.yearlyLabel','Yearly toggle'],['pricing.monthUnit','Monthly price unit'],['pricing.yearUnit','Yearly price unit'],['pricing.savingsLabel','Yearly savings note'],['pricing.popularLabel','Popular plan badge'],['pricing.chooseLabel','Choose plan button'],['pricing.manageLabel','Manage plan button'],['pricing.plans','Plans, prices and feature lists','json'],['pricing.footnote','Pricing note','textarea']]},
  {title:'Testimonials and FAQs',fields:[['testimonials.enabled','Show testimonials section','checkbox'],['testimonials.eyebrow','Testimonials label'],['testimonials.title','Testimonials heading'],['testimonials.items','Testimonial cards','json'],['faq.enabled','Show FAQs section','checkbox'],['faq.eyebrow','FAQ label'],['faq.title','FAQ heading'],['faq.items','Questions and answers','json']]},
  {title:'About and contact',fields:[['about.enabled','Show about section','checkbox'],['about.eyebrow','About label'],['about.title','About heading'],['about.description','About description','textarea'],['about.stats','About statistics','json'],['about.button','About button'],['about.href','About button link'],['contact.enabled','Show contact section','checkbox'],['contact.eyebrow','Contact label'],['contact.title','Contact heading'],['contact.description','Contact description','textarea'],['contact.email','Contact email'],['contact.submitLabel','Form button'],['contact.nameLabel','Name field label'],['contact.namePlaceholder','Name field placeholder'],['contact.emailLabel','Email field label'],['contact.emailPlaceholder','Email field placeholder'],['contact.messageLabel','Message field label'],['contact.messagePlaceholder','Message field placeholder'],['contact.successMessage','Success message']]},
  {title:'Promotion section',fields:[['promotions.enabled','Show promotions on homepage','checkbox'],['promotions.eyebrow','Promotion label'],['promotions.title','Promotion section heading'],['promotions.couponLabel','Coupon label'],['promotions.copyLabel','Copy-code button'],['promotions.defaultButton','Promotion link button']]},
  {title:'Closing section and footer',fields:[['finalCta.enabled','Show closing section','checkbox'],['finalCta.eyebrow','Closing label'],['finalCta.title','Closing heading (new line separates lines)','textarea'],['finalCta.description','Closing description','textarea'],['finalCta.button','Closing button'],['finalCta.href','Closing button link'],['trusted.enabled','Show trusted brands section','checkbox'],['trusted.title','Trusted brands heading'],['trusted.brands','Brand names','json'],['footer.enabled','Show footer','checkbox'],['footer.tagline','Footer text'],['footer.contactLabel','Footer contact link']]},
]

export default function MarketingWebsiteContentPage(){
  const storedUser=useMemo(()=>{try{return JSON.parse(localStorage.getItem('user')||'null')}catch{return null}},[])
  const [websites,setWebsites]=useState([]),[websiteId,setWebsiteId]=useState(storedUser?.role==='website_user'?(storedUser.websiteId||''):(new URLSearchParams(location.search).get('websiteId')||''))
  const [content,setContent]=useState(()=>merge(defaultContent,{})),[jsonDrafts,setJsonDrafts]=useState({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const isMainAdmin=storedUser?.role==='main_admin'

  useEffect(()=>{api.get('/websites').then(({data})=>{const list=Array.isArray(data)?data:[];setWebsites(list);if(storedUser?.role==='website_user'&&!websiteId){const own=list.find(item=>String(item.userId)===String(storedUser.id||storedUser._id));if(own)setWebsiteId(own._id)}}).catch(()=>setWebsites([]))},[])
  useEffect(()=>{
    let active=true;setLoading(true);setError('');setNotice('')
    api.get('/marketing/site-content',{params:websiteId?{websiteId}:{}}).then(({data})=>{if(!active)return;const next=merge(defaultContent,data?.content||{});setContent(next);const drafts={};groups.forEach(group=>group.fields.forEach(([path,,type])=>{if(type==='json')drafts[path]=JSON.stringify(getPath(next,path),null,2)}));setJsonDrafts(drafts)}).catch(err=>{if(active){setContent(merge(defaultContent,{}));setError(err.response?.data?.message||'Website content could not be loaded. Create your Marketing website first.')}}).finally(()=>{if(active)setLoading(false)})
    return()=>{active=false}
  },[websiteId])

  const update=(path,value)=>setContent(current=>setPath(current,path,value))
  const save=async event=>{
    event.preventDefault();setError('');setNotice('');let payload=content
    try{groups.forEach(group=>group.fields.forEach(([path,label,type])=>{if(type==='json')payload=setPath(payload,path,JSON.parse(jsonDrafts[path]||'null'))}));if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('Website content must be a JSON object.')}catch(parseError){setError(`Check the JSON field: ${parseError.message}`);return}
    setSaving(true)
    try{const {data}=await api.put('/marketing/site-content',{websiteId:websiteId||undefined,content:payload});setContent(merge(defaultContent,data.content||{}));setNotice('Website content saved. Your public page updates automatically.')}catch(err){setError(err.response?.data?.message||'Could not save website content.')}finally{setSaving(false)}
  }

  return <main className="mx-auto max-w-6xl space-y-5 pb-10">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Admin / Web / Marketing</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Website Content</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Edit the public Marketing website from this admin. Content is saved to the selected tenant website.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700"><Globe2 size={15}/>{websiteId?'Tenant website':'Platform website'}</span></header>
    {isMainAdmin&&<label className="grid max-w-xl gap-1.5 text-xs font-semibold text-slate-600">Choose website<select value={websiteId} onChange={event=>{setWebsiteId(event.target.value);if(event.target.value)history.replaceState(null,'',`?websiteId=${encodeURIComponent(event.target.value)}`);else history.replaceState(null,'',location.pathname)}} className="rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm font-normal"><option value="">Platform Marketing website</option>{websites.map(site=><option key={site._id} value={site._id}>{site.name || 'Untitled Marketing site'} · {site.status || 'draft'}</option>)}</select></label>}
    {!isMainAdmin&&storedUser?.role==='website_user'&&!websiteId&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">Create your Marketing website in <a href="/website-builder" className="font-semibold underline">Design Website</a> first. This editor will save content to that website only.</div>}
    {error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{notice&&<div role="status" className="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{notice}</div>}
    <form onSubmit={save} className="space-y-4">{groups.map((group,index)=><details key={group.title} open={index===0||index===1} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><summary className="cursor-pointer border-b border-slate-100 px-5 py-4 text-sm font-bold text-slate-900">{group.title}</summary><div className="grid gap-4 p-5 md:grid-cols-2">{group.fields.map(([path,label,type])=><label key={path} className={`grid gap-1.5 text-xs font-semibold text-slate-600 ${type==='json'||type==='textarea'?'md:col-span-2':''}`}>{type==='checkbox'?<span className="flex items-center gap-2"><input type="checkbox" checked={Boolean(getPath(content,path))} onChange={event=>update(path,event.target.checked)} className="h-4 w-4 accent-orange-600"/>{label}</span>:label}{type==='json'?<textarea spellCheck="false" rows={Math.min(16,Math.max(5,(jsonDrafts[path]||'').split('\n').length))} value={jsonDrafts[path]||''} onChange={event=>setJsonDrafts(current=>({...current,[path]:event.target.value}))} className="rounded-lg border border-slate-300 px-3 py-2.5 font-mono text-xs font-normal"/>:type==='textarea'?<textarea rows={3} value={getPath(content,path)??''} onChange={event=>update(path,event.target.value)} className="rounded-lg border border-slate-300 px-3 py-2.5 text-sm font-normal"/>:type!=='checkbox'&&<input type={type==='color'||type==='url'?type:'text'} value={getPath(content,path)??''} onChange={event=>update(path,event.target.value)} className={`rounded-lg border border-slate-300 px-3 py-2.5 text-sm font-normal ${type==='color'?'h-12 w-24 p-1':''}`}/>}{type==='json'&&<small className="font-normal text-slate-400">Valid JSON required. Edit the list or object shown here; the website uses these values directly.</small>}</label>)}</div></details>)}
      <div className="sticky bottom-3 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur"><span className="text-xs text-slate-500">Changes are scoped to {websiteId?'this tenant website':'the platform Marketing website'}.</span><button type="submit" disabled={saving||loading} className="inline-flex items-center gap-2 rounded-lg bg-orange-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><Save size={16}/>{saving?'Saving…':'Save website content'}</button></div>
    </form>
  </main>
}
