import { Layers, Image, Gift, Bell, Megaphone } from 'lucide-react';

export const PROMOTION_MODULES = {
  campaigns: {
    type: 'campaigns',
    title: 'Campaigns',
    description: 'Wepzo marketing campaigns — seasonal, store-wise aur festival offers',
    icon: Layers,
    iconBg: 'bg-violet-50',
    iconColor: 'text-violet-600',
    breadcrumb: 'Campaigns',
    fields: [
      { key: 'title', label: 'Campaign Title', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'store', label: 'Store', type: 'select', options: ['All Stores', 'ShriKart', "Mummy's Food", 'Krishiv Ethnic Wear', 'FreshMart Sitabuldi', 'Tech Hub Store'] },
      { key: 'type', label: 'Type', type: 'select', options: ['Seasonal', 'Store', 'Festival', 'Flash'] },
      { key: 'budget', label: 'Budget (₹)', type: 'number' },
      { key: 'startDate', label: 'Start Date' },
      { key: 'endDate', label: 'End Date' },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'store', label: 'Store', className: 'text-teal-600' },
      { key: 'type', label: 'Type' },
      { key: 'budget', label: 'Budget', render: v => `₹ ${Number(v || 0).toLocaleString('en-IN')}` },
      { key: 'reach', label: 'Reach' },
      { key: 'startDate', label: 'Start' },
      { key: 'endDate', label: 'End' },
      { key: 'status', label: 'Status', badge: true },
    ],
  },
  banners: {
    type: 'banners',
    title: 'Banners',
    description: 'Home aur category banners manage karein',
    icon: Image,
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-600',
    breadcrumb: 'Banners',
    fields: [
      { key: 'title', label: 'Banner Title', required: true },
      { key: 'subtitle', label: 'Subtitle', type: 'textarea' },
      { key: 'image', label: 'Banner image URL' },
      { key: 'cta', label: 'Button text' },
      { key: 'placement', label: 'Placement', type: 'select', options: ['Home Top', 'Home Mid', 'Category', 'Store Page'] },
      { key: 'store', label: 'Store', type: 'select', options: ['All Stores', 'ShriKart', 'FreshMart Sitabuldi', 'Tech Hub Store'] },
      { key: 'link', label: 'Link URL' },
      { key: 'priority', label: 'Priority', type: 'number' },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'placement', label: 'Placement' },
      { key: 'store', label: 'Store', className: 'text-teal-600' },
      { key: 'priority', label: 'Priority' },
      { key: 'link', label: 'Link', className: 'text-xs text-gray-500 max-w-[120px] truncate' },
      { key: 'status', label: 'Status', badge: true },
    ],
  },
  'other-banners': {
    type: 'other-banners',
    title: 'Other Banners',
    description: 'Checkout, profile aur store page ke promotional strips',
    icon: Image,
    iconBg: 'bg-cyan-50',
    iconColor: 'text-cyan-600',
    breadcrumb: 'Other Banners',
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'subtitle', label: 'Description', type: 'textarea' },
      { key: 'image', label: 'Banner image URL' },
      { key: 'link', label: 'Link URL' },
      { key: 'cta', label: 'Button text' },
      { key: 'section', label: 'Section', type: 'select', options: ['Checkout', 'Profile', 'Store Page', 'Cart'] },
      { key: 'store', label: 'Store', type: 'select', options: ['All Stores', 'Sweet Corner', 'ShriKart'] },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'section', label: 'Section' },
      { key: 'store', label: 'Store', className: 'text-teal-600' },
      { key: 'status', label: 'Status', badge: true },
    ],
  },
  coupons: {
    type: 'coupons',
    title: 'Coupons',
    description: 'Discount codes aur coupon offers',
    icon: Gift,
    iconBg: 'bg-pink-50',
    iconColor: 'text-pink-600',
    breadcrumb: 'Coupons',
    fields: [
      { key: 'code', label: 'Coupon Code', required: true },
      { key: 'title', label: 'Title', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'discount', label: 'Discount', required: true },
      { key: 'minOrder', label: 'Min Order (₹)', type: 'number' },
      { key: 'store', label: 'Store', type: 'select', options: ['All Stores', 'FreshMart Sitabuldi', 'Krishiv Ethnic Wear'] },
      { key: 'usageLimit', label: 'Usage Limit', type: 'number' },
      { key: 'expiry', label: 'Expiry Date' },
    ],
    columns: [
      { key: 'code', label: 'Code', className: 'font-mono font-bold text-primary-600' },
      { key: 'title', label: 'Title' },
      { key: 'discount', label: 'Discount', className: 'font-semibold text-green-600' },
      { key: 'minOrder', label: 'Min Order', render: v => `₹${v}` },
      { key: 'store', label: 'Store', className: 'text-teal-600' },
      { key: 'usedCount', label: 'Used' },
      { key: 'expiry', label: 'Expiry' },
      { key: 'status', label: 'Status', badge: true },
    ],
  },
  'push-notifications': {
    type: 'push-notifications',
    title: 'Push Notification',
    description: 'App users ko push notifications bhejein',
    icon: Bell,
    iconBg: 'bg-amber-50',
    iconColor: 'text-amber-600',
    breadcrumb: 'Push Notification',
    fields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'message', label: 'Message', type: 'textarea', required: true },
      { key: 'audience', label: 'Audience', type: 'select', options: ['All Users', 'Delivered Orders', 'Wallet Users', 'New Users'] },
      { key: 'scheduledAt', label: 'Schedule At' },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'message', label: 'Message', className: 'text-xs text-gray-500 max-w-[180px] truncate' },
      { key: 'audience', label: 'Audience' },
      { key: 'scheduledAt', label: 'Scheduled' },
      { key: 'sentCount', label: 'Sent' },
      { key: 'status', label: 'Status', badge: true },
    ],
  },
  advertisements: {
    type: 'advertisements',
    title: 'Advertisement',
    description: 'Google, Meta aur YouTube ads track karein',
    icon: Megaphone,
    iconBg: 'bg-orange-50',
    iconColor: 'text-orange-600',
    breadcrumb: 'Advertisement',
    fields: [
      { key: 'title', label: 'Ad Title', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'image', label: 'Image URL' },
      { key: 'link', label: 'Destination URL' },
      { key: 'platform', label: 'Platform', type: 'select', options: ['Google Ads', 'Meta Ads', 'YouTube', 'In-App'] },
      { key: 'store', label: 'Store', type: 'select', options: ['All Stores', 'FreshMart Sitabuldi', 'Krishiv Ethnic Wear', 'Tech Hub Store'] },
      { key: 'budget', label: 'Budget (₹)', type: 'number' },
    ],
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'platform', label: 'Platform' },
      { key: 'store', label: 'Store', className: 'text-teal-600' },
      { key: 'budget', label: 'Budget', render: v => `₹ ${Number(v || 0).toLocaleString('en-IN')}` },
      { key: 'impressions', label: 'Impressions' },
      { key: 'clicks', label: 'Clicks' },
      { key: 'status', label: 'Status', badge: true },
    ],
  },
};

export const STATUS_STYLES = {
  Active: 'bg-green-100 text-green-700',
  Scheduled: 'bg-blue-100 text-blue-700',
  Ended: 'bg-gray-100 text-gray-600',
  Inactive: 'bg-gray-100 text-gray-500',
  Expired: 'bg-red-100 text-red-700',
  Sent: 'bg-green-100 text-green-700',
  Draft: 'bg-amber-100 text-amber-700',
  Paused: 'bg-orange-100 text-orange-700',
};
