import {
  Settings, Globe, Eye, Users, Shield, CreditCard, Truck, Bell, Mail,
  Database, Link2, FolderOpen, ClipboardList, Smartphone, FileText, Building2,
  Store, ShoppingBag, RotateCcw, Bike, UserRound, SlidersHorizontal, Wallet, MessageSquareText,
} from 'lucide-react';

export const SETTINGS_HUB_CARDS = [
  {
    key: 'general',
    label: 'General Settings',
    path: '/settings/general',
    desc: 'Business info, logo, contact details, currency, language and basic settings',
    icon: Settings,
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-600',
  },
  {
    key: 'website',
    label: 'Website Settings',
    path: '/settings/website',
    desc: 'Manage homepage, header, footer, menus, banners, theme and SEO',
    icon: Globe,
    iconBg: 'bg-emerald-50',
    iconColor: 'text-emerald-600',
  },
  {
    key: 'visibility',
    label: 'Website Visibility',
    path: '/settings/visibility',
    desc: 'Control what to show or hide on website (products, categories, stores, etc.)',
    icon: Eye,
    iconBg: 'bg-violet-50',
    iconColor: 'text-violet-600',
  },
  {
    key: 'employees',
    label: 'Employee Management',
    path: '/settings/employees',
    desc: 'Add, manage and control employee accounts',
    icon: Users,
    iconBg: 'bg-orange-50',
    iconColor: 'text-orange-500',
  },
  {
    key: 'roles',
    label: 'Roles & Permissions',
    path: '/settings/employee-roles',
    desc: 'Create roles and set module-wise access permissions',
    icon: Shield,
    iconBg: 'bg-red-50',
    iconColor: 'text-red-500',
  },
  {
    key: 'payment',
    label: 'Payment Settings',
    path: '/settings/payment',
    desc: 'Manage payment methods, gateways, COD, tax, commission and refunds',
    icon: CreditCard,
    iconBg: 'bg-sky-50',
    iconColor: 'text-sky-600',
  },
  {
    key: 'delivery',
    label: 'Delivery Settings',
    path: '/settings/zones/delivery',
    desc: 'Configure delivery zones, charges, time, free delivery and rider settings',
    icon: Truck,
    iconBg: 'bg-green-50',
    iconColor: 'text-green-600',
  },
  {
    key: 'notifications',
    label: 'Notification Settings',
    path: '/settings/notifications',
    desc: 'Push, email and SMS notification settings',
    icon: Bell,
    iconBg: 'bg-pink-50',
    iconColor: 'text-pink-500',
  },
  {
    key: 'emailSms',
    label: 'Email & SMS Settings',
    path: '/settings/email-sms',
    desc: 'SMTP, SMS gateway, templates and OTP settings',
    icon: Mail,
    iconBg: 'bg-amber-50',
    iconColor: 'text-amber-500',
  },
  {
    key: 'security',
    label: 'Security Settings',
    path: '/settings/security',
    desc: 'Password policy, 2FA, login security, IP restrictions and logs',
    icon: Shield,
    iconBg: 'bg-rose-50',
    iconColor: 'text-rose-500',
  },
  {
    key: 'users',
    label: 'User Management',
    path: '/settings/users',
    desc: 'Manage customers, groups, blocked users and activity logs',
    icon: Users,
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-600',
  },
  {
    key: 'database',
    label: 'Database & System',
    path: '/settings/database',
    desc: 'Backup, restore, cache, file manager and system information',
    icon: Database,
    iconBg: 'bg-teal-50',
    iconColor: 'text-teal-600',
  },
  {
    key: 'api',
    label: 'API & Integration',
    path: '/settings/api',
    desc: 'Google API, Maps, Payment API, SMS API, WhatsApp API and webhooks',
    icon: Link2,
    iconBg: 'bg-purple-50',
    iconColor: 'text-purple-600',
  },
  {
    key: 'backup',
    label: 'Backup & Restore',
    path: '/settings/backup',
    desc: 'Create and manage backups, auto backup and restore',
    icon: FolderOpen,
    iconBg: 'bg-orange-50',
    iconColor: 'text-orange-500',
  },
  {
    key: 'audit',
    label: 'Audit & Activity Logs',
    path: '/settings/audit-logs',
    desc: 'Track admin, employee, order, product and system activities',
    icon: ClipboardList,
    iconBg: 'bg-indigo-50',
    iconColor: 'text-indigo-600',
  },
];

export const SETTINGS_PAGE_FORMS = {
  general: {
    title: 'General Settings',
    subtitle: 'Business info, logo, contact details, currency, language and basic settings',
    icon: Settings,
    fields: [
      { key: 'platformName', label: 'Business / Platform Name', type: 'text' },
      { key: 'supportEmail', label: 'Contact Email', type: 'email' },
      { key: 'supportPhone', label: 'Contact Phone', type: 'text' },
      { key: 'currency', label: 'Currency', type: 'text' },
      { key: 'language', label: 'Default Language', type: 'select', options: ['English', 'Hindi'] },
      { key: 'timezone', label: 'Timezone', type: 'text' },
      { key: 'logoUrl', label: 'Logo URL', type: 'text' },
      { key: 'address', label: 'Business Address', type: 'textarea', span: 2 },
      { key: 'maintenanceMode', label: 'Maintenance Mode', type: 'toggle' },
    ],
  },
  website: {
    title: 'Website Settings',
    subtitle: 'Homepage, header, footer, menus, banners, theme and SEO',
    icon: Globe,
    fields: [
      { key: 'siteTitle', label: 'Site Title', type: 'text' },
      { key: 'metaDescription', label: 'Meta Description', type: 'textarea', span: 2 },
      { key: 'headerMenu', label: 'Header Menu Items', type: 'text' },
      { key: 'footerText', label: 'Footer Text', type: 'text' },
      { key: 'themeColor', label: 'Theme Color', type: 'text' },
      { key: 'homepageBanner', label: 'Homepage Banner URL', type: 'text' },
      { key: 'showSearchBar', label: 'Show Search Bar', type: 'toggle' },
      { key: 'seoEnabled', label: 'Enable SEO tags', type: 'toggle' },
    ],
  },
  visibility: {
    title: 'Website Visibility',
    subtitle: 'Control what to show or hide on the website',
    icon: Eye,
    fields: [
      { key: 'showProducts', label: 'Show Products', type: 'toggle' },
      { key: 'showCategories', label: 'Show Categories', type: 'toggle' },
      { key: 'showStores', label: 'Show Stores', type: 'toggle' },
      { key: 'showReviews', label: 'Show Reviews', type: 'toggle' },
      { key: 'showOutOfStock', label: 'Show Out of Stock Items', type: 'toggle' },
      { key: 'showGuestPrices', label: 'Show Prices to Guests', type: 'toggle' },
    ],
  },
  app: {
    title: 'App Settings',
    subtitle: 'Customer, store and rider app configuration',
    icon: Smartphone,
    fields: [
      { key: 'androidAppUrl', label: 'Android App URL', type: 'text' },
      { key: 'iosAppUrl', label: 'iOS App URL', type: 'text' },
      { key: 'appMinVersion', label: 'Minimum App Version', type: 'text' },
      { key: 'forceUpdate', label: 'Force App Update', type: 'toggle' },
      { key: 'appMaintenance', label: 'App Maintenance Mode', type: 'toggle' },
      { key: 'enablePushInApp', label: 'Enable In-app Push', type: 'toggle' },
    ],
  },
  payment: {
    title: 'Payment Settings',
    subtitle: 'Payment methods, gateways, COD, tax, commission and refunds',
    icon: CreditCard,
    relatedLinks: [{ label: 'Tax Information', path: '/settings/zones/tax' }],
    fields: [
      { key: 'codEnabled', label: 'Cash on Delivery (COD)', type: 'toggle' },
      { key: 'onlinePaymentEnabled', label: 'Online Payments', type: 'toggle' },
      { key: 'offlinePaymentEnabled', label: 'Offline Payment', type: 'toggle' },
      { key: 'combinedPaymentEnabled', label: 'Allow Combined Payment', type: 'toggle' },
      { key: 'customerWalletEnabled', label: 'Customer Wallet', type: 'toggle' },
      { key: 'razorpayEnabled', label: 'Razorpay', type: 'toggle' },
      { key: 'stripeEnabled', label: 'Stripe', type: 'toggle' },
      { key: 'defaultCommission', label: 'Default Commission (%)', type: 'number' },
      { key: 'refundWindowDays', label: 'Refund Window (days)', type: 'number' },
      { key: 'razorpayKey', label: 'Razorpay Key ID', type: 'text' },
      { key: 'paymentCurrency', label: 'Payment Currency', type: 'text' },
    ],
  },
  vendor: {
    title: 'Vendor Settings',
    subtitle: 'Vendor registration, approval, and commission rules',
    icon: Store,
    fields: [
      { key: 'vendorCanCancelOrder', label: 'Vendor Can Cancel Order', type: 'toggle' },
      { key: 'vendorRegistrationEnabled', label: 'Vendor Self Registration', type: 'toggle' },
      { key: 'vendorProductGalleryEnabled', label: 'Product Gallery', type: 'toggle' },
      { key: 'vendorCanAccessAllProducts', label: 'Access All Products', type: 'toggle' },
      { key: 'vendorCanReplyReviews', label: 'Vendor Can Reply Review', type: 'toggle' },
      { key: 'vendorApprovalRequired', label: 'Need Approval For Products', type: 'toggle' },
      { key: 'vendorApprovalNewProduct', label: 'Approve New Products', type: 'toggle' },
      { key: 'vendorApprovalExistingProduct', label: 'Approve Product Updates', type: 'toggle' },
      { key: 'vendorUpdatePriceAllowed', label: 'Allow Price Updates', type: 'toggle' },
      { key: 'vendorUpdateVariationAllowed', label: 'Allow Variation Updates', type: 'toggle' },
      { key: 'vendorUpdateProductDetailsAllowed', label: 'Allow Product Detail Updates', type: 'toggle' },
      { key: 'cashInHandEnabled', label: 'Cash In Hand Overflow', type: 'toggle' },
      { key: 'cashInHandMax', label: 'Maximum Cash In Hand', type: 'number' },
      { key: 'cashInHandMin', label: 'Minimum Amount To Pay', type: 'number' },
    ],
  },
  orders: {
    title: 'Order Settings',
    subtitle: 'Order confirmation, cancellation, and scheduling rules',
    icon: ShoppingBag,
    fields: [
      { key: 'homeDeliveryEnabled', label: 'Home Delivery', type: 'toggle' },
      { key: 'takeawayEnabled', label: 'Takeaway', type: 'toggle' },
      { key: 'scheduledOrderEnabled', label: 'Scheduled Order', type: 'toggle' },
      { key: 'scheduledOrderInterval', label: 'Time Interval For Scheduled Delivery', type: 'number' },
      { key: 'scheduledOrderIntervalUnit', label: 'Scheduled Delivery Interval Unit', type: 'text' },
      { key: 'adminOrderNotificationEnabled', label: 'Order Notification for Admin', type: 'toggle' },
      { key: 'adminOrderNotificationType', label: 'Order Notification Type', type: 'text' },
      { key: 'freeDeliveryEnabled', label: 'Free Delivery Setup', type: 'toggle' },
      { key: 'freeDeliveryOption', label: 'Free Delivery Option', type: 'text' },
      { key: 'extraPackagingChargeEnabled', label: 'Enable Extra Packaging Charge', type: 'toggle' },
      { key: 'extraPackagingCharge', label: 'Extra Packaging Charge Amount', type: 'number' },
      { key: 'placeOrderByPrescription', label: 'Place Order by Prescription', type: 'toggle' },
      { key: 'orderDeliveryVerification', label: 'Order Delivery Verification', type: 'toggle' },
      { key: 'orderConfirmationBy', label: 'Who Will Confirm Order', type: 'text' },
      { key: 'orderCancellationReasons', label: 'Order Cancellation Reasons', type: 'textarea' },
    ],
  },
  refund: {
    title: 'Refund Settings',
    subtitle: 'Refund eligibility and processing controls',
    icon: RotateCcw,
    fields: [
      { key: 'refundRequestMode', label: 'Refund Request Mode', type: 'toggle' },
      { key: 'refundReasons', label: 'Refund Reasons', type: 'textarea' },
      { key: 'refundEnabled', label: 'Enable Refunds', type: 'toggle' },
      { key: 'refundWindowDays', label: 'Refund Window (days)', type: 'number' },
      { key: 'refundProcessingDays', label: 'Refund Processing Time (days)', type: 'number' },
      { key: 'refundAutoApproveLimit', label: 'Auto Approve Below Amount', type: 'number' },
      { key: 'refundReturnRequired', label: 'Require Item Return', type: 'toggle' },
    ],
  },
  deliveryman: {
    title: 'Deliveryman Settings',
    subtitle: 'Delivery partner assignment and service controls',
    icon: Bike,
    fields: [
      { key: 'deliverymanRegistrationEnabled', label: 'Deliveryman Registration', type: 'toggle' },
      { key: 'deliverymanMaxAssignedOrders', label: 'Maximum Assigned Order Limit', type: 'number' },
      { key: 'deliverymanCanCancelOrder', label: 'Deliveryman Can Cancel Order', type: 'toggle' },
      { key: 'deliverymanTipsEnabled', label: 'Tips For Deliveryman', type: 'toggle' },
      { key: 'deliverymanShowEarnings', label: 'Show Earnings in App', type: 'toggle' },
      { key: 'deliverymanProofOfDelivery', label: 'Take Picture for Delivery Completing', type: 'toggle' },
      { key: 'deliverymanAutoAssign', label: 'Automatically Assign Rider', type: 'toggle' },
      { key: 'deliverymanCommissionRate', label: 'Deliveryman Commission (%)', type: 'number' },
      { key: 'deliverymanAssignmentRadiusKm', label: 'Rider Assignment Radius (km)', type: 'number' },
      { key: 'deliverymanCanReject', label: 'Allow Rider to Reject Orders', type: 'toggle' },
      { key: 'deliverymanSuspendCashOverflow', label: 'Suspend On Cash In Hand Overflow', type: 'toggle' },
      { key: 'deliverymanCashInHandMax', label: 'Cash In Hand Max Amount', type: 'number' },
      { key: 'deliverymanCashMinPayout', label: 'Minimum Payable Amount', type: 'number' },
      { key: 'deliverymanLoyaltyEnabled', label: 'Deliveryman Loyalty Point', type: 'toggle' },
      { key: 'deliverymanLoyaltyEarnPerOrder', label: 'Loyalty Point Earn Per Order', type: 'number' },
      { key: 'deliverymanLoyaltyCurrencyEquivalent', label: 'Currency Equivalent To Points', type: 'number' },
      { key: 'deliverymanLoyaltyMinimumConvert', label: 'Minimum Points To Convert', type: 'number' },
      { key: 'deliverymanReferralEnabled', label: 'Deliveryman Referral Earning', type: 'toggle' },
      { key: 'deliverymanReferralEarn', label: 'Earning Per Referral', type: 'number' },
      { key: 'deliverymanReferralBonus', label: 'Referral Bonus In Wallet', type: 'number' },
    ],
  },
  customer: {
    title: 'Customer Settings',
    subtitle: 'Customer account, checkout, and wallet options',
    icon: UserRound,
    fields: [
      { key: 'customerRegistrationEnabled', label: 'Customer Registration', type: 'toggle' },
      { key: 'customerEmailVerification', label: 'Verify Customer Email', type: 'toggle' },
      { key: 'customerPhoneVerification', label: 'Verify Customer Phone', type: 'toggle' },
      { key: 'customerGuestCheckout', label: 'Allow Guest Checkout', type: 'toggle' },
      { key: 'customerFoodPreferenceEnabled', label: 'Customer Food Preference', type: 'toggle' },
      { key: 'customerWalletEnabled', label: 'Customer Wallet', type: 'toggle' },
      { key: 'customerRefundToWalletEnabled', label: 'Refund to Wallet', type: 'toggle' },
      { key: 'customerAddFundsEnabled', label: 'Add Fund to Wallet', type: 'toggle' },
      { key: 'customerLoyaltyEnabled', label: 'Customer Loyalty Point', type: 'toggle' },
      { key: 'customerLoyaltyCurrencyEquivalent', label: 'Currency Equivalent to Points', type: 'number' },
      { key: 'customerLoyaltyEarnPercent', label: 'Loyalty Point Earn Per Order (%)', type: 'number' },
      { key: 'customerLoyaltyMinimumConvert', label: 'Minimum Points Required to Convert', type: 'number' },
      { key: 'customerReferralEnabled', label: 'Customer Referral Earning', type: 'toggle' },
      { key: 'customerReferralEarn', label: 'Earning Per Referral', type: 'number' },
      { key: 'customerReferralDiscountEnabled', label: 'Discount for Referred Customer', type: 'toggle' },
      { key: 'customerReferralDiscountPercent', label: 'Referral Discount Amount (%)', type: 'number' },
      { key: 'customerReferralDiscountValidityMonths', label: 'Referral Discount Validity (months)', type: 'number' },
    ],
  },
  priority: {
    title: 'Priority Setup',
    subtitle: 'Configure priority and featured listing defaults',
    icon: SlidersHorizontal,
    fields: [
      { key: 'priorityListingEnabled', label: 'Enable Priority Listings', type: 'toggle' },
      { key: 'priorityFeaturedEnabled', label: 'Enable Featured Listings', type: 'toggle' },
      { key: 'prioritySponsoredEnabled', label: 'Enable Sponsored Listings', type: 'toggle' },
      { key: 'priorityDefaultRank', label: 'Default Priority Rank', type: 'number' },
      { key: 'priorityUseDefaultSorting', label: 'Use Default Sorting', type: 'toggle' },
      { key: 'priorityUseCustomSorting', label: 'Use Custom Sorting', type: 'toggle' },
      ...[
        'bestStoresNearby', 'recommendedStore', 'specialOffers', 'mostPopularItem', 'bestReviewedItem',
        'justForYou', 'newOnSomoo', 'allStores', 'categorySubcategoryProducts', 'productSearch',
        'basicMedicineNearby', 'commonCondition', 'brand', 'brandWiseProducts', 'topOfferNearMe',
      ].flatMap(key => [
        { key: `priority_${key}_default`, label: `${key} Default Sort`, type: 'toggle' },
        { key: `priority_${key}_custom`, label: `${key} Custom Sort`, type: 'toggle' },
        { key: `priority_${key}_sort`, label: `${key} Custom Sort Order`, type: 'text' },
        ...(['mostPopularItem', 'bestReviewedItem', 'justForYou', 'categorySubcategoryProducts', 'productSearch', 'basicMedicineNearby', 'brandWiseProducts'].includes(key) ? [
          { key: `priority_${key}_stockHandling`, label: `${key} Stock Handling`, type: 'text' },
          { key: `priority_${key}_storeHandling`, label: `${key} Store Availability Handling`, type: 'text' },
        ] : []),
      ]),
    ],
  },
  disbursement: {
    title: 'Disbursement Settings',
    subtitle: 'Configure vendor payout timing and minimums',
    icon: Wallet,
    fields: [
      { key: 'disbursementEnabled', label: 'Enable Disbursements', type: 'toggle' },
      { key: 'disbursementRequestType', label: 'Disbursement Request Type', type: 'text' },
      { key: 'disbursementSchedule', label: 'Payout Schedule', type: 'select', options: ['Daily', 'Weekly', 'Biweekly', 'Monthly'] },
      { key: 'disbursementMinimum', label: 'Minimum Payout Amount', type: 'number' },
      { key: 'disbursementProcessingDays', label: 'Processing Time (days)', type: 'number' },
      { key: 'disbursementAutoProcess', label: 'Automatically Process Eligible Payouts', type: 'toggle' },
      { key: 'bankAccountVerificationEnabled', label: 'Enable Bank Account Verification', type: 'toggle' },
      { key: 'razorpayFullAccountVerification', label: 'Use Razorpay For Full Account Number Verification', type: 'toggle' },
      { key: 'razorpaySourceAccountNumber', label: 'Razorpay Source Account Number', type: 'text' },
    ],
  },
  automatedMessage: {
    title: 'Automated Messages',
    subtitle: 'Manage customer and vendor messages sent automatically',
    icon: MessageSquareText,
    fields: [
      { key: 'automatedOrderMessages', label: 'Order Status Messages', type: 'toggle' },
      { key: 'automatedRefundMessages', label: 'Refund Messages', type: 'toggle' },
      { key: 'automatedVendorMessages', label: 'Vendor Messages', type: 'toggle' },
      { key: 'automatedOrderPlacedText', label: 'Order Placed Message', type: 'textarea', span: 2 },
      { key: 'automatedOrderDeliveredText', label: 'Order Delivered Message', type: 'textarea', span: 2 },
      { key: 'automatedMessageReasons', label: 'Automated Message Reasons', type: 'textarea' },
    ],
  },
  delivery: {
    title: 'Delivery Settings',
    subtitle: 'Delivery zones, charges, time, free delivery and rider settings',
    icon: Truck,
    relatedLinks: [{ label: 'Zone Setup', path: '/settings/zones' }],
    fields: [
      { key: 'baseDeliveryCharge', label: 'Base Delivery Charge', type: 'number' },
      { key: 'freeDeliveryMin', label: 'Free Delivery Minimum Order', type: 'number' },
      { key: 'deliveryEtaMin', label: 'Default ETA (minutes)', type: 'number' },
      { key: 'maxDeliveryKm', label: 'Max Delivery Distance (km)', type: 'number' },
      { key: 'riderCommission', label: 'Rider Commission (%)', type: 'number' },
      { key: 'enableScheduledDelivery', label: 'Scheduled Delivery', type: 'toggle' },
      { key: 'enableExpressDelivery', label: 'Express Delivery', type: 'toggle' },
    ],
  },
  notifications: {
    title: 'Notification Settings',
    subtitle: 'Push, email and SMS notification preferences',
    icon: Bell,
    fields: [
      { key: 'notifyOrderPlaced', label: 'Order Placed', type: 'toggle' },
      { key: 'notifyOrderDelivered', label: 'Order Delivered', type: 'toggle' },
      { key: 'notifyRefund', label: 'Refund Updates', type: 'toggle' },
      { key: 'notifyNewStore', label: 'New Store Request', type: 'toggle' },
      { key: 'pushEnabled', label: 'Push Notifications', type: 'toggle' },
      { key: 'emailNotifyEnabled', label: 'Email Notifications', type: 'toggle' },
      { key: 'smsNotifyEnabled', label: 'SMS Notifications', type: 'toggle' },
    ],
  },
  emailSms: {
    title: 'Email & SMS Settings',
    subtitle: 'SMTP, SMS gateway, templates and OTP',
    icon: Mail,
    fields: [
      { key: 'smtpHost', label: 'SMTP Host', type: 'text' },
      { key: 'smtpPort', label: 'SMTP Port', type: 'text' },
      { key: 'smtpUser', label: 'SMTP Username', type: 'text' },
      { key: 'smtpFrom', label: 'From Email', type: 'email' },
      { key: 'smsGateway', label: 'SMS Gateway', type: 'select', options: ['MSG91', 'Twilio', 'Textlocal'] },
      { key: 'smsSenderId', label: 'SMS Sender ID', type: 'text' },
      { key: 'otpLength', label: 'OTP Length', type: 'number' },
      { key: 'otpExpiryMin', label: 'OTP Expiry (minutes)', type: 'number' },
    ],
  },
  security: {
    title: 'Security Settings',
    subtitle: 'Password policy, 2FA, login security and IP restrictions',
    icon: Shield,
    fields: [
      { key: 'minPasswordLength', label: 'Min Password Length', type: 'number' },
      { key: 'sessionTimeoutMin', label: 'Session Timeout (minutes)', type: 'number' },
      { key: 'maxLoginAttempts', label: 'Max Login Attempts', type: 'number' },
      { key: 'allowedIps', label: 'Allowed IPs (comma separated)', type: 'text' },
      { key: 'twoFactorEnabled', label: 'Two-Factor Authentication', type: 'toggle' },
      { key: 'forceStrongPassword', label: 'Force Strong Passwords', type: 'toggle' },
      { key: 'lockInactiveAdmins', label: 'Lock Inactive Admins', type: 'toggle' },
    ],
  },
  database: {
    title: 'Database & System',
    subtitle: 'Cache, file manager and system information',
    icon: Database,
    relatedLinks: [
      { label: 'Backup & Restore', path: '/settings/backup' },
      { label: 'System Logs', path: '/settings/system-logs' },
    ],
    fields: [
      { key: 'cacheDriver', label: 'Cache Driver', type: 'select', options: ['Memory', 'Redis', 'File'] },
      { key: 'cacheTtlMin', label: 'Cache TTL (minutes)', type: 'number' },
      { key: 'maxUploadMb', label: 'Max Upload Size (MB)', type: 'number' },
      { key: 'debugMode', label: 'Debug Mode', type: 'toggle' },
      { key: 'autoClearCache', label: 'Auto Clear Cache Daily', type: 'toggle' },
    ],
  },
  api: {
    title: 'API & Integration',
    subtitle: 'Google, Maps, Payment, SMS, WhatsApp APIs and webhooks',
    icon: Link2,
    fields: [
      { key: 'googleMapsKey', label: 'Google Maps API Key', type: 'text' },
      { key: 'googleAnalyticsId', label: 'Google Analytics ID', type: 'text' },
      { key: 'whatsappApiToken', label: 'WhatsApp API Token', type: 'text' },
      { key: 'webhookUrl', label: 'Webhook URL', type: 'text' },
      { key: 'fcmServerKey', label: 'FCM Server Key', type: 'text' },
      { key: 'enableWebhooks', label: 'Enable Webhooks', type: 'toggle' },
    ],
  },
  backup: {
    title: 'Backup & Restore',
    subtitle: 'Create backups, auto backup and restore',
    icon: FolderOpen,
    fields: [
      { key: 'autoBackup', label: 'Auto Backup', type: 'toggle' },
      { key: 'backupFrequency', label: 'Backup Frequency', type: 'select', options: ['Daily', 'Weekly', 'Monthly'] },
      { key: 'backupRetentionDays', label: 'Retention (days)', type: 'number' },
      { key: 'lastBackupAt', label: 'Last Backup', type: 'text', readOnly: true },
    ],
  },
};

export const SETTINGS_FORM_DEFAULTS = {
  language: 'English',
  logoUrl: '',
  address: 'Nagpur, Maharashtra, India',
  siteTitle: 'WEPZO',
  metaDescription: 'WEPZO multi-vendor commerce platform',
  headerMenu: 'Home, Shops, Categories, Offers',
  footerText: '© 2026 WEPZO. All rights reserved.',
  themeColor: '#2563eb',
  homepageBanner: '',
  showSearchBar: true,
  seoEnabled: true,
  showProducts: true,
  showCategories: true,
  showStores: true,
  showReviews: true,
  showOutOfStock: true,
  showGuestPrices: true,
  androidAppUrl: '',
  iosAppUrl: '',
  appMinVersion: '1.0.0',
  forceUpdate: false,
  appMaintenance: false,
  enablePushInApp: true,
  codEnabled: true,
  onlinePaymentEnabled: true,
  razorpayEnabled: true,
  stripeEnabled: false,
  refundWindowDays: 7,
  razorpayKey: '',
  paymentCurrency: 'INR',
  baseDeliveryCharge: 30,
  freeDeliveryMin: 499,
  deliveryEtaMin: 30,
  maxDeliveryKm: 12,
  riderCommission: 15,
  enableScheduledDelivery: true,
  enableExpressDelivery: false,
  notifyOrderPlaced: true,
  notifyOrderDelivered: true,
  notifyRefund: true,
  notifyNewStore: true,
  pushEnabled: true,
  emailNotifyEnabled: true,
  smsNotifyEnabled: false,
  smtpHost: 'smtp.wepzo.com',
  smtpPort: '587',
  smtpUser: 'noreply@wepzo.com',
  smtpFrom: 'noreply@wepzo.com',
  smsGateway: 'MSG91',
  smsSenderId: 'WEPZO',
  otpLength: 6,
  otpExpiryMin: 5,
  minPasswordLength: 8,
  sessionTimeoutMin: 60,
  maxLoginAttempts: 5,
  allowedIps: '',
  twoFactorEnabled: false,
  forceStrongPassword: true,
  lockInactiveAdmins: false,
  cacheDriver: 'Memory',
  cacheTtlMin: 30,
  maxUploadMb: 10,
  debugMode: false,
  autoClearCache: true,
  googleMapsKey: '',
  googleAnalyticsId: '',
  whatsappApiToken: '',
  webhookUrl: '',
  fcmServerKey: '',
  enableWebhooks: false,
  autoBackup: true,
  backupFrequency: 'Daily',
  backupRetentionDays: 14,
  lastBackupAt: '20 Sep 2026, 02:30 AM',
  environment: 'Production',
  phpVersion: '8.1.0',
  dbVersion: 'MySQL 8.0',
  serverOs: 'Linux',
  appVersion: 'v1.0.0',
};

export const EXTRA_NAV_ICONS = { Building2, Smartphone, FileText };
