import {
  Settings, Globe, Eye, Users, Shield, CreditCard, Truck, Bell, Mail,
  Database, Link2, FolderOpen, ClipboardList, Smartphone, FileText, Building2,
} from 'lucide-react';

export const SETTINGS_HUB_CARDS = [
  {
    key: 'general',
    label: 'General Settings',
    path: '/settings/general',
    desc: 'Business info, logo, contact details, currency, language and basic settings',
    icon: Settings,
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-600',
  },
  {
    key: 'website',
    label: 'Website Settings',
    path: '/settings/website',
    desc: 'Manage homepage, header, footer, menus, banners, theme and SEO',
    icon: Globe,
    iconBg: 'bg-emerald-50',
    iconColor: 'text-emerald-600',
  },
  {
    key: 'visibility',
    label: 'Website Visibility',
    path: '/settings/visibility',
    desc: 'Control what to show or hide on website (products, categories, stores, etc.)',
    icon: Eye,
    iconBg: 'bg-violet-50',
    iconColor: 'text-violet-600',
  },
  {
    key: 'employees',
    label: 'Employee Management',
    path: '/settings/employees',
    desc: 'Add, manage and control employee accounts',
    icon: Users,
    iconBg: 'bg-orange-50',
    iconColor: 'text-orange-500',
  },
  {
    key: 'roles',
    label: 'Roles & Permissions',
    path: '/settings/employee-roles',
    desc: 'Create roles and set module-wise access permissions',
    icon: Shield,
    iconBg: 'bg-red-50',
    iconColor: 'text-red-500',
  },
  {
    key: 'payment',
    label: 'Payment Settings',
    path: '/settings/payment',
    desc: 'Manage payment methods, gateways, COD, tax, commission and refunds',
    icon: CreditCard,
    iconBg: 'bg-sky-50',
    iconColor: 'text-sky-600',
  },
  {
    key: 'delivery',
    label: 'Delivery Settings',
    path: '/settings/zones/delivery',
    desc: 'Configure delivery zones, charges, time, free delivery and rider settings',
    icon: Truck,
    iconBg: 'bg-green-50',
    iconColor: 'text-green-600',
  },
  {
    key: 'notifications',
    label: 'Notification Settings',
    path: '/settings/notifications',
    desc: 'Push, email and SMS notification settings',
    icon: Bell,
    iconBg: 'bg-pink-50',
    iconColor: 'text-pink-500',
  },
  {
    key: 'emailSms',
    label: 'Email & SMS Settings',
    path: '/settings/email-sms',
    desc: 'SMTP, SMS gateway, templates and OTP settings',
    icon: Mail,
    iconBg: 'bg-amber-50',
    iconColor: 'text-amber-500',
  },
  {
    key: 'security',
    label: 'Security Settings',
    path: '/settings/security',
    desc: 'Password policy, 2FA, login security, IP restrictions and logs',
    icon: Shield,
    iconBg: 'bg-rose-50',
    iconColor: 'text-rose-500',
  },
  {
    key: 'users',
    label: 'User Management',
    path: '/settings/users',
    desc: 'Manage customers, groups, blocked users and activity logs',
    icon: Users,
    iconBg: 'bg-blue-50',
    iconColor: 'text-blue-600',
  },
  {
    key: 'database',
    label: 'Database & System',
    path: '/settings/database',
    desc: 'Backup, restore, cache, file manager and system information',
    icon: Database,
    iconBg: 'bg-teal-50',
    iconColor: 'text-teal-600',
  },
  {
    key: 'api',
    label: 'API & Integration',
    path: '/settings/api',
    desc: 'Google API, Maps, Payment API, SMS API, WhatsApp API and webhooks',
    icon: Link2,
    iconBg: 'bg-purple-50',
    iconColor: 'text-purple-600',
  },
  {
    key: 'backup',
    label: 'Backup & Restore',
    path: '/settings/backup',
    desc: 'Create and manage backups, auto backup and restore',
    icon: FolderOpen,
    iconBg: 'bg-orange-50',
    iconColor: 'text-orange-500',
  },
  {
    key: 'audit',
    label: 'Audit & Activity Logs',
    path: '/settings/audit-logs',
    desc: 'Track admin, employee, order, product and system activities',
    icon: ClipboardList,
    iconBg: 'bg-indigo-50',
    iconColor: 'text-indigo-600',
  },
];

export const SETTINGS_PAGE_FORMS = {
  general: {
    title: 'General Settings',
    subtitle: 'Business info, logo, contact details, currency, language and basic settings',
    icon: Settings,
    fields: [
      { key: 'platformName', label: 'Business / Platform Name', type: 'text' },
      { key: 'supportEmail', label: 'Contact Email', type: 'email' },
      { key: 'supportPhone', label: 'Contact Phone', type: 'text' },
      { key: 'currency', label: 'Currency', type: 'text' },
      { key: 'language', label: 'Default Language', type: 'select', options: ['English', 'Hindi'] },
      { key: 'timezone', label: 'Timezone', type: 'text' },
      { key: 'logoUrl', label: 'Logo URL', type: 'text' },
      { key: 'address', label: 'Business Address', type: 'textarea', span: 2 },
      { key: 'maintenanceMode', label: 'Maintenance Mode', type: 'toggle' },
    ],
  },
  website: {
    title: 'Website Settings',
    subtitle: 'Homepage, header, footer, menus, banners, theme and SEO',
    icon: Globe,
    fields: [
      { key: 'siteTitle', label: 'Site Title', type: 'text' },
      { key: 'metaDescription', label: 'Meta Description', type: 'textarea', span: 2 },
      { key: 'headerMenu', label: 'Header Menu Items', type: 'text' },
      { key: 'footerText', label: 'Footer Text', type: 'text' },
      { key: 'themeColor', label: 'Theme Color', type: 'text' },
      { key: 'homepageBanner', label: 'Homepage Banner URL', type: 'text' },
      { key: 'showSearchBar', label: 'Show Search Bar', type: 'toggle' },
      { key: 'seoEnabled', label: 'Enable SEO tags', type: 'toggle' },
    ],
  },
  visibility: {
    title: 'Website Visibility',
    subtitle: 'Control what to show or hide on the website',
    icon: Eye,
    fields: [
      { key: 'showProducts', label: 'Show Products', type: 'toggle' },
      { key: 'showCategories', label: 'Show Categories', type: 'toggle' },
      { key: 'showStores', label: 'Show Stores', type: 'toggle' },
      { key: 'showReviews', label: 'Show Reviews', type: 'toggle' },
      { key: 'showOutOfStock', label: 'Show Out of Stock Items', type: 'toggle' },
      { key: 'showGuestPrices', label: 'Show Prices to Guests', type: 'toggle' },
    ],
  },
  app: {
    title: 'App Settings',
    subtitle: 'Customer, store and rider app configuration',
    icon: Smartphone,
    fields: [
      { key: 'androidAppUrl', label: 'Android App URL', type: 'text' },
      { key: 'iosAppUrl', label: 'iOS App URL', type: 'text' },
      { key: 'appMinVersion', label: 'Minimum App Version', type: 'text' },
      { key: 'forceUpdate', label: 'Force App Update', type: 'toggle' },
      { key: 'appMaintenance', label: 'App Maintenance Mode', type: 'toggle' },
      { key: 'enablePushInApp', label: 'Enable In-app Push', type: 'toggle' },
    ],
  },
  payment: {
    title: 'Payment Settings',
    subtitle: 'Payment methods, gateways, COD, tax, commission and refunds',
    icon: CreditCard,
    relatedLinks: [{ label: 'Tax Information', path: '/settings/zones/tax' }],
    fields: [
      { key: 'codEnabled', label: 'Cash on Delivery (COD)', type: 'toggle' },
      { key: 'onlinePaymentEnabled', label: 'Online Payments', type: 'toggle' },
      { key: 'razorpayEnabled', label: 'Razorpay', type: 'toggle' },
      { key: 'stripeEnabled', label: 'Stripe', type: 'toggle' },
      { key: 'defaultCommission', label: 'Default Commission (%)', type: 'number' },
      { key: 'refundWindowDays', label: 'Refund Window (days)', type: 'number' },
      { key: 'razorpayKey', label: 'Razorpay Key ID', type: 'text' },
      { key: 'paymentCurrency', label: 'Payment Currency', type: 'text' },
    ],
  },
  delivery: {
    title: 'Delivery Settings',
    subtitle: 'Delivery zones, charges, time, free delivery and rider settings',
    icon: Truck,
    relatedLinks: [{ label: 'Zone Setup', path: '/settings/zones' }],
    fields: [
      { key: 'baseDeliveryCharge', label: 'Base Delivery Charge', type: 'number' },
      { key: 'freeDeliveryMin', label: 'Free Delivery Minimum Order', type: 'number' },
      { key: 'deliveryEtaMin', label: 'Default ETA (minutes)', type: 'number' },
      { key: 'maxDeliveryKm', label: 'Max Delivery Distance (km)', type: 'number' },
      { key: 'riderCommission', label: 'Rider Commission (%)', type: 'number' },
      { key: 'enableScheduledDelivery', label: 'Scheduled Delivery', type: 'toggle' },
      { key: 'enableExpressDelivery', label: 'Express Delivery', type: 'toggle' },
    ],
  },
  notifications: {
    title: 'Notification Settings',
    subtitle: 'Push, email and SMS notification preferences',
    icon: Bell,
    fields: [
      { key: 'notifyOrderPlaced', label: 'Order Placed', type: 'toggle' },
      { key: 'notifyOrderDelivered', label: 'Order Delivered', type: 'toggle' },
      { key: 'notifyRefund', label: 'Refund Updates', type: 'toggle' },
      { key: 'notifyNewStore', label: 'New Store Request', type: 'toggle' },
      { key: 'pushEnabled', label: 'Push Notifications', type: 'toggle' },
      { key: 'emailNotifyEnabled', label: 'Email Notifications', type: 'toggle' },
      { key: 'smsNotifyEnabled', label: 'SMS Notifications', type: 'toggle' },
    ],
  },
  emailSms: {
    title: 'Email & SMS Settings',
    subtitle: 'SMTP, SMS gateway, templates and OTP',
    icon: Mail,
    fields: [
      { key: 'smtpHost', label: 'SMTP Host', type: 'text' },
      { key: 'smtpPort', label: 'SMTP Port', type: 'text' },
      { key: 'smtpUser', label: 'SMTP Username', type: 'text' },
      { key: 'smtpFrom', label: 'From Email', type: 'email' },
      { key: 'smsGateway', label: 'SMS Gateway', type: 'select', options: ['MSG91', 'Twilio', 'Textlocal'] },
      { key: 'smsSenderId', label: 'SMS Sender ID', type: 'text' },
      { key: 'otpLength', label: 'OTP Length', type: 'number' },
      { key: 'otpExpiryMin', label: 'OTP Expiry (minutes)', type: 'number' },
    ],
  },
  security: {
    title: 'Security Settings',
    subtitle: 'Password policy, 2FA, login security and IP restrictions',
    icon: Shield,
    fields: [
      { key: 'minPasswordLength', label: 'Min Password Length', type: 'number' },
      { key: 'sessionTimeoutMin', label: 'Session Timeout (minutes)', type: 'number' },
      { key: 'maxLoginAttempts', label: 'Max Login Attempts', type: 'number' },
      { key: 'allowedIps', label: 'Allowed IPs (comma separated)', type: 'text' },
      { key: 'twoFactorEnabled', label: 'Two-Factor Authentication', type: 'toggle' },
      { key: 'forceStrongPassword', label: 'Force Strong Passwords', type: 'toggle' },
      { key: 'lockInactiveAdmins', label: 'Lock Inactive Admins', type: 'toggle' },
    ],
  },
  database: {
    title: 'Database & System',
    subtitle: 'Cache, file manager and system information',
    icon: Database,
    relatedLinks: [
      { label: 'Backup & Restore', path: '/settings/backup' },
      { label: 'System Logs', path: '/settings/system-logs' },
    ],
    fields: [
      { key: 'cacheDriver', label: 'Cache Driver', type: 'select', options: ['Memory', 'Redis', 'File'] },
      { key: 'cacheTtlMin', label: 'Cache TTL (minutes)', type: 'number' },
      { key: 'maxUploadMb', label: 'Max Upload Size (MB)', type: 'number' },
      { key: 'debugMode', label: 'Debug Mode', type: 'toggle' },
      { key: 'autoClearCache', label: 'Auto Clear Cache Daily', type: 'toggle' },
    ],
  },
  api: {
    title: 'API & Integration',
    subtitle: 'Google, Maps, Payment, SMS, WhatsApp APIs and webhooks',
    icon: Link2,
    fields: [
      { key: 'googleMapsKey', label: 'Google Maps API Key', type: 'text' },
      { key: 'googleAnalyticsId', label: 'Google Analytics ID', type: 'text' },
      { key: 'whatsappApiToken', label: 'WhatsApp API Token', type: 'text' },
      { key: 'webhookUrl', label: 'Webhook URL', type: 'text' },
      { key: 'fcmServerKey', label: 'FCM Server Key', type: 'text' },
      { key: 'enableWebhooks', label: 'Enable Webhooks', type: 'toggle' },
    ],
  },
  backup: {
    title: 'Backup & Restore',
    subtitle: 'Create backups, auto backup and restore',
    icon: FolderOpen,
    fields: [
      { key: 'autoBackup', label: 'Auto Backup', type: 'toggle' },
      { key: 'backupFrequency', label: 'Backup Frequency', type: 'select', options: ['Daily', 'Weekly', 'Monthly'] },
      { key: 'backupRetentionDays', label: 'Retention (days)', type: 'number' },
      { key: 'lastBackupAt', label: 'Last Backup', type: 'text', readOnly: true },
    ],
  },
};

export const SETTINGS_FORM_DEFAULTS = {
  language: 'English',
  logoUrl: '',
  address: 'Nagpur, Maharashtra, India',
  siteTitle: 'WEPZO',
  metaDescription: 'WEPZO multi-vendor commerce platform',
  headerMenu: 'Home, Shops, Categories, Offers',
  footerText: '© 2026 WEPZO. All rights reserved.',
  themeColor: '#2563eb',
  homepageBanner: '',
  showSearchBar: true,
  seoEnabled: true,
  showProducts: true,
  showCategories: true,
  showStores: true,
  showReviews: true,
  showOutOfStock: true,
  showGuestPrices: true,
  androidAppUrl: '',
  iosAppUrl: '',
  appMinVersion: '1.0.0',
  forceUpdate: false,
  appMaintenance: false,
  enablePushInApp: true,
  codEnabled: true,
  onlinePaymentEnabled: true,
  razorpayEnabled: true,
  stripeEnabled: false,
  refundWindowDays: 7,
  razorpayKey: '',
  paymentCurrency: 'INR',
  baseDeliveryCharge: 30,
  freeDeliveryMin: 499,
  deliveryEtaMin: 30,
  maxDeliveryKm: 12,
  riderCommission: 15,
  enableScheduledDelivery: true,
  enableExpressDelivery: false,
  notifyOrderPlaced: true,
  notifyOrderDelivered: true,
  notifyRefund: true,
  notifyNewStore: true,
  pushEnabled: true,
  emailNotifyEnabled: true,
  smsNotifyEnabled: false,
  smtpHost: 'smtp.wepzo.com',
  smtpPort: '587',
  smtpUser: 'noreply@wepzo.com',
  smtpFrom: 'noreply@wepzo.com',
  smsGateway: 'MSG91',
  smsSenderId: 'WEPZO',
  otpLength: 6,
  otpExpiryMin: 5,
  minPasswordLength: 8,
  sessionTimeoutMin: 60,
  maxLoginAttempts: 5,
  allowedIps: '',
  twoFactorEnabled: false,
  forceStrongPassword: true,
  lockInactiveAdmins: false,
  cacheDriver: 'Memory',
  cacheTtlMin: 30,
  maxUploadMb: 10,
  debugMode: false,
  autoClearCache: true,
  googleMapsKey: '',
  googleAnalyticsId: '',
  whatsappApiToken: '',
  webhookUrl: '',
  fcmServerKey: '',
  enableWebhooks: false,
  autoBackup: true,
  backupFrequency: 'Daily',
  backupRetentionDays: 14,
  lastBackupAt: '20 Sep 2026, 02:30 AM',
  environment: 'Production',
  phpVersion: '8.1.0',
  dbVersion: 'MySQL 8.0',
  serverOs: 'Linux',
  appVersion: 'v1.0.0',
};

export const EXTRA_NAV_ICONS = { Building2, Smartphone, FileText };
